<%@ Page Title="ניהול משתמשים" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="ManageUsers.aspx.cs" Inherits="ManageUsers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" 
        GridLines="None" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" OnPageIndexChanging="GridView1_PageIndexChanging" 
        OnRowCancelingEdit="GridView1_RowCancelingEdit" 
        OnRowEditing="GridView1_RowEditing" onrowdeleting="GridView1_RowDeleting" 
        onrowupdating="GridView1_RowUpdating" HorizontalAlign="Center" PageSize="15">
        <AlternatingRowStyle BackColor="White" />
        
        <Columns>
            <asp:BoundField DataField="email" HeaderText="אימייל משתמש" 
                SortExpression="email" ReadOnly="True" />
            <asp:BoundField DataField="fname" HeaderText="שם פרטי" SortExpression="fname" />
            <asp:BoundField DataField="lname" HeaderText="שם משפחה" 
                SortExpression="lname" />
            <asp:BoundField DataField="password" HeaderText="סיסמא" 
                SortExpression="password" />
            <asp:BoundField DataField="dateJoined" HeaderText="תאריך הרשמה" 
                SortExpression="credit" ReadOnly="True" />
            <asp:BoundField DataField="lastOnline" HeaderText="התחבר פעם אחרונה" 
                SortExpression="lastOnline" ReadOnly="True" />
            <asp:BoundField DataField="prem" HeaderText="הרשאה" 
                SortExpression="prem" />
        </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>

    <asp:Label ID="lbres" runat="server" 
        style="font-weight: 700; font-size: x-large" dir="rtl"></asp:Label>
    <br />
    <asp:Label ID="lbPrem" runat="server" 
        style="color: Red; font-weight: 700; font-size: x-large" ForeColor="Red" dir="rtl">אין לך הרשאה לראות דף זה.</asp:Label>
    </asp:Content>

